### ISSUE TITLE
I need this feature,s

### ISSUE THREAD

**Issue by SOURAV-2007** [Coders-src/discordpy-handler#1]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
#🎵 Support Source
 Youtube
 SoundCloud
 Spotify
 Bandcamp
 Vimeo
 Https (Radio)
--------------------------------------------------------------------------------
#🌟 Feature
 Music System
 Playlists System
 Custom Prefix
 Slash commands
 Custom Filters
 Easy to use

**Comment by anshtyagi0** [comment]
We already have custom prefix system.
And we have noted your request and will make it as soon as possible.
